const VALID_STATUS = '1' as const
const PENDING_STATUS = '2' as const
const INVALID_STATUS = '0' as const

const ARTICLE_STATUS = {
  VALID: VALID_STATUS,
  PENDING: PENDING_STATUS,
  INVALID: INVALID_STATUS
} as const

export { VALID_STATUS, PENDING_STATUS, INVALID_STATUS, ARTICLE_STATUS }
